name: Build and Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml

  qodana:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
